"""initial migration

Revision ID: 3eca8738fd40
Revises: 
Create Date: 2025-10-13 00:30:44.096464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eca8738fd40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('total_notes', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('lesson',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('color_theme', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('total_sections', sa.Integer(), nullable=True),
    sa.Column('completed_sections', sa.Integer(), nullable=True),
    sa.Column('total_time_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_user_id'), ['user_id'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    op.create_table('grade_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('drop_lowest', sa.Integer(), nullable=True),
    sa.Column('drop_highest', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('grading_scale', sa.Text(), nullable=False),
    sa.Column('grading_type', sa.String(length=20), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('passing_grade', sa.String(length=5), nullable=True),
    sa.Column('passing_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('show_total_grade', sa.Boolean(), nullable=True),
    sa.Column('allow_what_if', sa.Boolean(), nullable=True),
    sa.Column('show_class_average', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_table('grade_summary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('current_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_possible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('letter_grade', sa.String(length=5), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_passing', sa.Boolean(), nullable=True),
    sa.Column('points_to_pass', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points_to_next_grade', sa.Text(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uix_user_lesson_grade')
    )
    op.create_table('lesson_section',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_section_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_section_section_type'), ['section_type'], unique=False)

    op.create_table('grade_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_possible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_extra_credit', sa.Boolean(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('classwork_task_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['grade_category.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('grade_item_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points_possible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_excused', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('late_penalty', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_item_id'], ['grade_item.id'], ),
    sa.ForeignKeyConstraint(['graded_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_entry')
    op.drop_table('grade_item')
    with op.batch_alter_table('lesson_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_section_section_type'))
        batch_op.drop_index(batch_op.f('ix_lesson_section_lesson_id'))

    op.drop_table('lesson_section')
    op.drop_table('grade_summary')
    op.drop_table('grade_config')
    op.drop_table('grade_category')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_section_id'))
        batch_op.drop_index(batch_op.f('ix_task_priority'))
        batch_op.drop_index(batch_op.f('ix_task_lesson_id'))

    op.drop_table('task')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_user_id'))
        batch_op.drop_index(batch_op.f('ix_note_section_id'))
        batch_op.drop_index(batch_op.f('ix_note_note_type'))
        batch_op.drop_index(batch_op.f('ix_note_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_note_is_public'))

    op.drop_table('note')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_status'))
        batch_op.drop_index(batch_op.f('ix_lesson_source_platform'))
        batch_op.drop_index(batch_op.f('ix_lesson_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_lesson_external_id'))

    op.drop_table('lesson')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
